# Generated by Django 6.0.5 on 2026-06-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ats_score',
            field=models.IntegerField(default=0),
        ),
    ]
